# Site settings
title: "CWP"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cwp.mikegardner.me.uk" # the base hostname & protocol for your site
port: 			  4102

# Build settings
#markdown: kramdown
exclude: ["README.md"]

#source "https://rubygems.org"
#gem "github-pages", group: :jekyll_plugins
